#!/usr/bin/env python3
"""
D21-C: RPC Governance Inventory generator.

Runs tools/reports/rpc_governance_inventory.sql against the live database,
enriches every RPC with its real consumers (frontend + edge functions +
scheduled_jobs table via a second SQL pass), computes a Status column and
writes a consumable Markdown report to stdout.

Status rules (deterministic, no editorializing):
  RISK  = grants include PUBLIC or anon AND tenant_guard == 'none'
  WATCH = grants include PUBLIC or anon (guard present) OR consumers == 0 with wide grants
  OK    = grants scoped (authenticated/service_role) with tenant_guard != 'none'
  INFO  = anything else (e.g. internal-only, granted only to postgres/service_role)

Requires: PGCONN env var (postgres connection string). Reads the repo from CWD.
"""
from __future__ import annotations

import csv
import os
import re
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SQL = REPO / "tools/reports/rpc_governance_inventory.sql"

SEARCH_ROOTS = ["src", "supabase/functions", "e2e", "tests", "contracts"]
RPC_CALL_RE = re.compile(r"""\.rpc\(\s*['"`]([a-zA-Z0-9_]+)['"`]""")


def run_psql(sql_path: Path) -> str:
    conn = os.environ.get("PGCONN")
    if not conn:
        sys.exit("PGCONN env var is required.")
    result = subprocess.run(
        ["psql", conn, "-v", "ON_ERROR_STOP=1", "-X", "-q", "-f", str(sql_path)],
        capture_output=True, text=True, check=True,
    )
    return result.stdout


def scan_consumers() -> dict[str, list[str]]:
    """Map rpc_name -> list of relative file paths that call it."""
    consumers: dict[str, set[str]] = defaultdict(set)
    for root in SEARCH_ROOTS:
        root_path = REPO / root
        if not root_path.exists():
            continue
        for path in root_path.rglob("*"):
            if not path.is_file() or path.suffix not in {".ts", ".tsx", ".js", ".jsx"}:
                continue
            try:
                text = path.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                continue
            for match in RPC_CALL_RE.finditer(text):
                consumers[match.group(1)].add(str(path.relative_to(REPO)))
    return {k: sorted(v) for k, v in consumers.items()}


def classify(grants: str, tenant_guard: str, consumers_count: int) -> str:
    grantees = {g.strip() for g in grants.split(",") if g.strip()}
    wide = bool(grantees & {"PUBLIC", "anon"})
    scoped = bool(grantees & {"authenticated", "service_role"})

    if wide and tenant_guard == "none":
        return "RISK"
    if wide:
        return "WATCH"
    if scoped and tenant_guard != "none":
        return "OK"
    if consumers_count == 0 and grantees and grantees != {"postgres"}:
        return "WATCH"
    return "INFO"


def main() -> None:
    raw = run_psql(SQL)
    consumers = scan_consumers()

    rows = []
    for line in raw.splitlines():
        if not line.strip():
            continue
        parts = line.split("\t")
        if len(parts) != 7:
            continue
        rpc, owner, definer, grants, tenant_guard, auth_role, source_hash = parts
        name = rpc.split("(", 1)[0]
        callers = consumers.get(name, [])
        status = classify(grants, tenant_guard, len(callers))
        rows.append({
            "rpc": rpc,
            "owner": owner,
            "definer": definer,
            "grants": grants,
            "tenant_guard": tenant_guard,
            "auth_role": auth_role,
            "consumers": len(callers),
            "consumers_sample": ", ".join(callers[:3]) + (f" (+{len(callers) - 3})" if len(callers) > 3 else ""),
            "status": status,
            "source_hash": source_hash,
        })

    # Summary
    total = len(rows)
    by_status = defaultdict(int)
    for r in rows:
        by_status[r["status"]] += 1

    out = []
    out.append("# D21-C — RPC Governance Inventory\n")
    out.append(f"_Generated by `tools/reports/generate_rpc_governance_inventory.py` — {total} SECURITY DEFINER functions in `public`._\n")
    out.append("## Summary\n")
    out.append("| Status | Count |")
    out.append("|--------|-------|")
    for s in ["RISK", "WATCH", "OK", "INFO"]:
        out.append(f"| {s} | {by_status.get(s, 0)} |")
    out.append("")

    for group in ["RISK", "WATCH", "OK", "INFO"]:
        subset = [r for r in rows if r["status"] == group]
        if not subset:
            continue
        out.append(f"## {group} ({len(subset)})\n")
        out.append("| RPC | Owner | Definer | Grants | Tenant Guard | auth.role | Consumers | Sample |")
        out.append("|-----|-------|---------|--------|--------------|-----------|-----------|--------|")
        for r in subset:
            out.append(
                f"| `{r['rpc']}` | {r['owner']} | {r['definer']} | {r['grants']} | "
                f"{r['tenant_guard']} | {r['auth_role']} | {r['consumers']} | {r['consumers_sample'] or '—'} |"
            )
        out.append("")

    # Machine-readable CSV alongside
    csv_path = REPO / "docs/audits/active/d21-c-rpc-governance-inventory.csv"
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    with csv_path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()) if rows else ["rpc"])
        w.writeheader()
        w.writerows(rows)

    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
