/**
 * Installer Template Version Tracker
 * 
 * Este arquivo rastreia as versoes do installer template para facilitar
 * debugging e validacao de deploys.
 * 
 * IMPORTANTE: Atualizar este arquivo sempre que modificar installer-template.ts
 */

export const INSTALLER_VERSION = 'v3.10.8-AGENT-ID-FIX';
export const LAST_UPDATED = '2025-01-26T23:30:00Z'; // AGENT-ID-FIX: poll-jobs retorna agent_id, handlers usam $Job.agent_id

export const CHANGES = [
  '[v3.10.8-AGENT-ID-FIX] CRITICAL FIX: poll-jobs Edge Function agora retorna agent_id no objeto de resposta',
  '[v3.10.8-AGENT-ID-FIX] CRITICAL FIX: Handlers de seguranca (software_inventory, vuln_scan, antivirus, web_activity) usam $Job.agent_id',
  '[v3.10.8-AGENT-ID-FIX] FIX: Elimina erro 400 "agent_id violates not-null constraint" em jobs de seguranca',
  '[v3.10.8-AGENT-ID-FIX] FIX: Todos os security jobs agora completam com sucesso e populam tabelas corretamente',
  '[v3.10.7-FINAL-FIX] CRITICAL FIX: Bug #1 - scan handler removeu try/catch redundante que usava $result nao declarada',
  '[v3.10.7-FINAL-FIX] CRITICAL FIX: Bug #2 - scan handler corrigido para usar -Path ao inves de -Uri em Invoke-SecureRequest',
  '[v3.10.7-FINAL-FIX] CRITICAL FIX: Bug #3 - update_agent handler corrigido para usar -Path ao inves de -Uri',
  '[v3.10.7-FINAL-FIX] CRITICAL FIX: Bug #4 - Handlers de seguranca agora extraem $output de $result.output corretamente',
  '[v3.10.7-FINAL-FIX] CRITICAL FIX: Bug #5 - Metricas aparecem apos 5 minutos (comportamento correto mantido)',
  '[v3.10.7-FINAL-FIX] CRITICAL FIX: Bug #6 - Stuck jobs eliminados com correcao dos bugs acima',
  '[v3.10.7-FINAL-FIX] VALIDACAO: Testado em VM testepc2 com todos os tipos de jobs (scan, update_agent, security)',
  '[v3.10.5-UPDATE-FIX] CRITICAL FIX: Handler update_agent agora usa $output ao inves de variavel $result nao declarada',
  '[v3.10.5-UPDATE-FIX] CRITICAL FIX: Corrige erro "Exception setting property error" que impedia auto-update',
  '[v3.10.5-UPDATE-FIX] CRITICAL FIX: update_agent jobs agora completam corretamente permitindo auto-update funcionar',
  '[v3.10.4-UTF8-FIX] CRITICAL FIX: Forcado UTF-8 encoding em Invoke-SecureRequest para consistencia HMAC',
  '[v3.10.4-UTF8-FIX] CRITICAL FIX: Body JSON convertido para UTF-8 bytes antes de enviar (resolve erro 401 em submit-job-result)',
  '[v3.10.4-UTF8-FIX] CRITICAL FIX: HMAC agora calcula assinatura identica no agente PowerShell e backend Deno',
  '[v3.10.3-TLS-COMPLETE] CRITICAL FIX: TLS 1.2 no comando irm (resolve erro de download em Windows Server)',
  '[v3.10.3-TLS-COMPLETE] CRITICAL FIX: TLS 1.2 no installer template (resolve health check)',
  '[v3.10.3-TLS-COMPLETE] MELHORIA: TLS 1.2 em 3 camadas (download + installer + agent) para compatibilidade total',
  '[v3.10.2-TLS-FIX] CRITICAL FIX: Forcando TLS 1.2 no agente para compatibilidade com firewalls corporativos (pfSense)',
  '[v3.10.2-TLS-FIX] CRITICAL FIX: Configuracao automatica de proxy do sistema para ambientes corporativos',
  '[v3.10.2-TLS-FIX] FIX: Resolve erro "Nao foi possivel criar um canal seguro para SSL/TLS" em Windows Server',
  '[v3.10.2-TLS-FIX] MELHORIA: Heartbeat agora funciona atraves de firewalls Cloudflare/Supabase',
  '[v3.10.1-AGGRESSIVE-CLEANUP] FIX: Encerra processos PowerShell do agente antes da reinstalacao',
  '[v3.10.1-AGGRESSIVE-CLEANUP] FIX: Remove log antigo do agente preventivamente',
  '[v3.10.1-AGGRESSIVE-CLEANUP] FIX: Teste de escrita no log com retry (3 tentativas com 2s de intervalo)',
  '[v3.10.1-AGGRESSIVE-CLEANUP] FIX: Resolve erro "O fluxo nao era legivel" causado por log travado',
  '[v3.10.0-SECURITY-FEATURES] FEATURE: Software inventory collection (software_inventory_collect job)',
  '[v3.10.0-SECURITY-FEATURES] FEATURE: Light vulnerability scanner (light_vuln_scan job)',
  '[v3.10.0-SECURITY-FEATURES] FEATURE: Antivirus status collection (collect_antivirus_status job)',
  '[v3.10.0-SECURITY-FEATURES] FEATURE: Web activity tracking via DNS cache (collect_web_activity job)',
  '[v3.10.0-SECURITY-FEATURES] FEATURE: Auto-remediation - fix firewall (fix_firewall job)',
  '[v3.10.0-SECURITY-FEATURES] FEATURE: Auto-remediation - restart service (restart_service job)',
  '[v3.10.0-SECURITY-FEATURES] NEW: 12 tabelas de seguranca: software_inventory, vuln_findings, antivirus_status, agent_web_activity, etc',
  '[v3.10.0-SECURITY-FEATURES] NEW: 6 Edge Functions para coleta e analise de dados de seguranca',
  '[v3.9.1-JOB-TYPE-FIX] CRITICAL FIX: Submit-JobResult agora aceita [object] ao inves de [hashtable]',
  '[v3.9.1-JOB-TYPE-FIX] CRITICAL FIX: Jobs report agora completam corretamente (nao mais crash PSCustomObject)',
  '[v3.9.1-JOB-TYPE-FIX] FIX: Tipo do parametro $Output mudado para [object] para aceitar PSCustomObject',
  '[v3.9.0-AUTO-UPDATE] FEATURE: Agente verifica updates automaticamente a cada 24h via check-agent-updates',
  '[v3.9.0-AUTO-UPDATE] FEATURE: Auto-aplica updates quando nova versao disponivel (sem reinstalacao)',
  '[v3.9.0-AUTO-UPDATE] FEATURE: Edge Function register-agent-release para registrar novas versoes',
  '[v3.9.0-AUTO-UPDATE] FEATURE: Edge Function process-agent-updates com cron para push updates',
  '[v3.9.0-AUTO-UPDATE] MELHORIA: Tabelas agent_releases e agent_versions populadas com v3.8.0',
  '[v3.8.0-REALTIME-OS-TYPE-FIX] CRITICAL FIX: Agente envia os_type ao inves de platform no heartbeat',
  '[v3.8.0-REALTIME-OS-TYPE-FIX] CRITICAL FIX: Heartbeat aceita tanto os_type quanto platform (retrocompatibilidade)',
  '[v3.8.0-REALTIME-OS-TYPE-FIX] CRITICAL FIX: Realtime habilitado para agent_system_metrics e system_alerts',
  '[v3.8.0-REALTIME-OS-TYPE-FIX] CRITICAL FIX: Agentes existentes com os_type NULL atualizados para "windows"',
  '[v3.8.0-REALTIME-OS-TYPE-FIX] MELHORIA: Dashboard agora atualiza metricas em tempo real',
  '[v3.7.0-METRICS-WMI-FALLBACK] CRITICAL FIX: Cleanup jobs agora deleta jobs de qualquer idade (older_than_days: 0)',
  '[v3.7.0-METRICS-WMI-FALLBACK] CRITICAL FIX: Metricas CPU/RAM/Disco com WMI fallback quando Get-Counter falhar',
  '[v3.7.0-METRICS-WMI-FALLBACK] FIX: CPU usa Get-Counter primeiro, fallback para Win32_Processor.LoadPercentage',
  '[v3.7.0-METRICS-WMI-FALLBACK] FIX: RAM sempre via WMI Win32_OperatingSystem (mais confiavel)',
  '[v3.7.0-METRICS-WMI-FALLBACK] FIX: Disco usa Get-PSDrive primeiro, fallback para Win32_LogicalDisk',
  '[v3.7.0-METRICS-WMI-FALLBACK] MELHORIA: Jobs tipo report agora funcionam em VMs sem Performance Counters',
  '[v3.6.1-TELEMETRY-HMAC-FIX] CRITICAL FIX: Telemetria agora usa HMAC (X-Agent-Token + X-HMAC-Signature)',
  '[v3.6.1-TELEMETRY-HMAC-FIX] NOVO: Funcoes Convert-HexToBytes e Get-HmacSignature copiadas do agent',
  '[v3.6.1-TELEMETRY-HMAC-FIX] FIX: Installer envia post_installation com credenciais do agente',
  '[v3.6.1-TELEMETRY-HMAC-FIX] FIX: track-installation-event aceita qualquer event_type com HMAC valido',
  '[v3.6.1-TELEMETRY-HMAC-FIX] FIX: Fallback para telemetria anonima se agent ja existir (compatibilidade)',
  '[v3.6.0-METRICS-FIX] CRITICAL FIX: Metricas agora sao REALMENTE enviadas via POST submit-system-metrics',
  '[v3.6.0-METRICS-FIX] NOVO: Funcao Send-SystemMetrics envia payload estruturado para backend',
  '[v3.6.0-METRICS-FIX] FIX: Loop principal parseia JSON de Invoke-ReportJob e envia via HTTP',
  '[v3.6.0-METRICS-FIX] FIX: Logs agora mostram "CPU=XX%, RAM=YY%, Disco=ZZ%" quando metricas sao enviadas',
  '[v3.5.0-METRICS-AUTO] NOVO: Envio automatico de metricas a cada 5min no loop principal',
  '[v3.5.0-METRICS-AUTO] FIX: Calculadora de preco dinamica baseada em tiers (Landing)',
  '[v3.5.0-METRICS-AUTO] FIX: Dashboard com validacao robusta de agents online',
  '[v3.5.0-METRICS-AUTO] FIX: Telemetria aceita X-Agent-Token para post_installation (nao apenas installation_failed)',
  '[v3.5.0-METRICS-AUTO] NOVO: Cleanup automatico de jobs stuck (delivered >1h)',
  'FIX: Corrige header de versao do script (v3.0.0 -> v3.4.0-REPORT-SUPPORT)',
  'FIX: Sincroniza version string entre source e embedded script',
  'NOVO: Adiciona suporte para jobs do tipo "report" com coleta de metricas do sistema',
  'NOVO: Funcao Invoke-ReportJob coleta CPU, memoria e disco (uso de percentual)',
  'NOVO: Logging de rede em todas as requisicoes HTTP (method + URL + status)',
  'MELHORIA: Switch de tipos de job agora suporta: integration_test, collect_info, report, scan, update_agent',
  'PREVIO: Corrige InvalidVariableReferenceWithDrive no payload HMAC (linha 199)',
  'PREVIO: Substitui "$timestamp:$nonce:$bodyJson" por formatacao explicita \'{0}:{1}:{2}\' -f',
  'PREVIO: Usa operador -f para garantir compatibilidade total com PowerShell 5.1',
  'PREVIO: Diagnostico avancado de restricoes de seguranca (GPO, AppLocker, LanguageMode, AV/EDR)',
  'PREVIO: Detecta GPO forcando ExecutionPolicy AllSigned/Restricted',
  'PREVIO: Detecta Constrained Language Mode (Device Guard/WDAC)',
  'PREVIO: Testa AppLocker com execucao basica de script',
  'PREVIO: Verifica eventos do Windows Defender relacionados a PowerShell',
  'PREVIO: Detecta Device Guard / WDAC Code Integrity enforcement',
  'PREVIO: Script standalone diagnose-security-restrictions.ps1',
  'PREVIO: Adiciona Unblock-File apos salvar script do agente',
  'PREVIO: Adiciona fallback para remover Zone.Identifier manualmente',
  'PREVIO: ExecutionPolicy alterado de Bypass para Unrestricted',
  'Adiciona validacao de Zone.Identifier antes e depois do desbloqueio',
  'Corrige PSSecurityException: UnauthorizedAccess em ambientes restritos',
  'PREVIO: Scheduled Task arguments com double-double quotes ("")',
  'Corrige erro 4294770688 (argumentos mal formatados) causado por escaping incorreto',
  'PREVIO: Write-InstallerLog movida para ANTES de qualquer uso (linha ~57)',
  'Criacao de pastas agora e silenciosa (FASE 0), logging inicia na FASE 1',
  'Corrige erro: The term Write-InstallerLog is not recognized',
  'Previo: LINE-CONTINUATION-REMOVED + InvalidVariableReferenceWithDrive fixes',
  'Code Guardian System valida automaticamente sintaxe PowerShell 5.1',
];

export const KNOWN_ISSUES_FIXED = [
  'CRITICAL: Jobs nao completavam devido a erro "Nao e possivel converter PSCustomObject para Hashtable" (v3.9.1)',
  'CRITICAL: Submit-JobResult esperava [hashtable] mas recebia PSCustomObject de ConvertFrom-Json',
  'CRITICAL: Cleanup jobs nao deletava nada (older_than_days: 7 bloqueava jobs recentes)',
  'CRITICAL: Metricas N/A em VMs sem Performance Counters habilitados',
  'CRITICAL: Get-Counter falhava silenciosamente, sem fallback para WMI',
  'CRITICAL: Jobs tipo report falhavam completamente em ambientes restritos',
  'InvalidVariableReferenceWithDrive: PowerShell 5.1 interpretava :$ como drive reference no payload HMAC (CRITICAL)',
  'PSSecurityException ao executar script como SYSTEM (CRITICAL)',
  'Zone.Identifier bloqueando execucao mesmo com -ExecutionPolicy Bypass',
  'UnauthorizedAccess em ambientes com ExecutionPolicy restritiva',
  'Script marcado como "da internet" impede execucao pela Scheduled Task',
  'Task Scheduler Error 4294770688: argumentos mal formatados (CRITICAL)',
  'Backtick-quote escaping incompativel com New-ScheduledTaskAction',
  'The term Write-InstallerLog is not recognized as the name of a cmdlet',
  'ParserError: ExpectedValueExpression apos operador + (continuacao de linha)',
  'InvalidVariableReferenceWithDrive: : $_ em mensagens de log',
  'Instalador falhava com erros de parse antes de executar',
  'Agent nao conseguia logar erros corretamente',
  'Continuacoes de linha do PowerShell causando problemas em String.raw',
];

/**
 * Retorna string formatada para logs
 */
export function getVersionInfo(): string {
  return `Installer v${INSTALLER_VERSION} (${LAST_UPDATED})`;
}
