/**
 * Installer Template Version Tracker
 * 
 * Este arquivo rastreia as versoes do installer template para facilitar
 * debugging e validacao de deploys.
 * 
 * IMPORTANTE: Atualizar este arquivo sempre que modificar installer-template.ts
 */

export const INSTALLER_VERSION = 'v3.10.31-SUBMIT-BEFORE-EXIT';
export const INSTALLER_VERSION_LINUX = 'v3.10.30-UPTIME';
export const INSTALLER_VERSION_MACOS = 'v3.10.30-UPTIME';
export const LAST_UPDATED = '2025-12-09T23:45:00Z'; // Windows synced to v3.10.31-SUBMIT-BEFORE-EXIT

export const CHANGES = [
  '[v3.10.31-SUBMIT-BEFORE-EXIT] CRITICAL FIX: update_agent e reinstall_agent agora submetem resultado ANTES de exit 0',
  '[v3.10.31-SUBMIT-BEFORE-EXIT] CRITICAL FIX: Resolve jobs stuck em delivered (nunca recebiam completion)',
  '[v3.10.31-SUBMIT-BEFORE-EXIT] CRITICAL FIX: Agentes nao ficam mais offline apos auto-update',
  '[v3.10.30-UPTIME] FEATURE: Coleta de uptime_seconds e last_boot_time para todos os agentes',
  '[v3.10.30-UPTIME] FEATURE: Windows usa WMI Win32_OperatingSystem.LastBootUpTime',
  '[v3.10.30-UPTIME] FEATURE: Linux usa /proc/uptime para calcular uptime_seconds',
  '[v3.10.30-UPTIME] FEATURE: macOS usa sysctl kern.boottime para calcular uptime',
  '[v3.10.30-UPTIME] FIX: Dashboard agora exibe coluna "Tempo Ligado" com valor real',
  '[v3.10.29-FORCED-RESTART] CRITICAL FIX: update_agent agora encerra processo atual com exit 0 apos iniciar nova task',
  '[v3.10.29-FORCED-RESTART] CRITICAL FIX: Nova versao assume imediatamente, nao precisa mais aguardar reboot',
  '[v3.10.28-WEB-ACTIVITY-DEDUP-FIX] P0 FIX: Deduplicacao de web activity usando hashtable ao inves de Sort-Object -Unique',
  '[v3.10.28-WEB-ACTIVITY-DEDUP-FIX] P0 FIX: Sort-Object -Unique nao funciona corretamente com hashtables',
  '[v3.10.28-WEB-ACTIVITY-DEDUP-FIX] P0 FIX: Edge Function submit-web-activity agora loga payload invalido detalhadamente',
  '[v3.10.27-SCAN-RETRY-BACKOFF] P1 FIX: Scan handler com retry e exponential backoff para reduzir falhas',
  '[v3.10.27-SCAN-RETRY-BACKOFF] P1 FIX: 4 tentativas com delays de 5s, 10s, 20s, 40s para 429/erros',
  '[v3.10.27-SCAN-RETRY-BACKOFF] P1 FIX: Log detalhado de cada tentativa de scan para debugging',
  '[v3.10.26-RATE-LIMIT-BACKOFF] P1 FIX: Exponential backoff para erros 429 (rate limiting)',
  '[v3.10.25-LINUX-SYNC] FEATURE: Agente Linux sincronizado com features do Windows v3.10.25',
  '[v3.10.25-LINUX-SYNC] FEATURE: sync_blocked_websites - sincroniza dominios bloqueados em /opt/cybershield/blocked_websites.json',
  '[v3.10.25-LINUX-SYNC] FEATURE: update_agent com smart path detection (PSCommandPath, AgentName, glob, fallback)',
  '[v3.10.25-LINUX-SYNC] FEATURE: collect_web_activity multi-usuario (itera /home/* para Chrome/Firefox)',
  '[v3.10.25-LINUX-SYNC] FEATURE: software_inventory_collect (dpkg, rpm, snap, flatpak)',
  '[v3.10.25-LINUX-SYNC] FEATURE: collect_antivirus_status (ClamAV, Sophos)',
  '[v3.10.25-LINUX-SYNC] FEATURE: fix_firewall (ufw, firewalld, iptables)',
  '[v3.10.25-LINUX-SYNC] FEATURE: restart_service via systemctl',
  '[v3.10.25-LINUX-SYNC] FEATURE: collect_network_info (gateway, DNS, IP publico)',
  '[v3.10.25-LINUX-SYNC] FEATURE: light_vuln_scan (SSH config, permissoes, SUID)',
  '[v3.10.25-LINUX-SYNC] FEATURE: Auto-update check a cada 24h',
  '[v3.10.25-BLOCKED-WEBSITES] FEATURE: Novo job type sync_blocked_websites para sincronizar lista de sites bloqueados',
  '[v3.10.25-BLOCKED-WEBSITES] FEATURE: Salva lista de dominios bloqueados em C:\\CyberShield\\blocked_websites.json',
  '[v3.10.25-BLOCKED-WEBSITES] FEATURE: Opcao apply_to_hosts para bloquear dominios via Windows hosts file',
  '[v3.10.25-BLOCKED-WEBSITES] FEATURE: Limpa DNS cache apos modificar hosts file para aplicar imediatamente',
  '[v3.10.24-SMART-UPDATE] CRITICAL FIX: update_agent agora detecta automaticamente o path do script atual',
  '[v3.10.24-SMART-UPDATE] CRITICAL FIX: Tenta multiplas estrategias: PSCommandPath, AgentName, glob pattern',
  '[v3.10.24-SMART-UPDATE] CRITICAL FIX: Pula backup se script atual nao encontrado (nao falha)',
  '[v3.10.24-SMART-UPDATE] CRITICAL FIX: Recria Scheduled Task com path correto garantindo futuras execucoes',
  '[v3.10.24-SMART-UPDATE] NOVO: Job type reinstall_agent para reinstalacao completa remota',
  '[v3.10.24-SMART-UPDATE] NOVO: reinstall_agent remove todas as tasks e scripts antigos, instala versao mais recente',
  '[v3.10.23-NETSH-FALLBACK] P0 FIX: Funcao Get-FirewallProfilesSafe com fallback netsh para sistemas antigos',
  '[v3.10.23-NETSH-FALLBACK] P0 FIX: Fix-Firewall agora usa netsh advfirewall se Set-NetFirewallProfile indisponivel',
  '[v3.10.23-NETSH-FALLBACK] P0 FIX: Vuln scan e network-info usam funcao com fallback',
  '[v3.10.22-WEB-ACTIVITY-DEDUP] CRITICAL FIX: Web activity agora envia $uniqueItems ao inves de $items (linha 827)',
  '[v3.10.22-WEB-ACTIVITY-DEDUP] CRITICAL FIX: Elimina duplicatas enviadas para submit-web-activity',
  '[v3.10.22-WEB-ACTIVITY-DEDUP] DEFESA: Deduplicacao server-side no Edge Function como fallback',
  '[v3.10.21-OPEN-PORTS-FIX] FIX: Open ports collection usando Get-NetTCPConnection ao inves de netstat',
  '[v3.10.20-NETWORK-INFO] FEATURE: Novo job type collect_network_info para coleta de diagnostico de rede',
  '[v3.10.20-NETWORK-INFO] FEATURE: Coleta status do Windows Firewall (Domain/Private/Public)',
  '[v3.10.20-NETWORK-INFO] FEATURE: Coleta portas abertas (listening) com processo associado',
  '[v3.10.20-NETWORK-INFO] FEATURE: Coleta conexoes ativas (established) com endereco remoto',
  '[v3.10.20-NETWORK-INFO] FEATURE: Coleta adaptadores de rede com IP e MAC',
  '[v3.10.20-NETWORK-INFO] FEATURE: Coleta DNS servers, gateway IP e IP publico',
  '[v3.10.20-NETWORK-INFO] FEATURE: Testes de conectividade DNS e HTTPS automaticos',
  '[v3.10.19-VERSION-NORMALIZE] CRITICAL FIX: Edge Functions agora normalizam versoes removendo prefixo "v" antes de comparar',
  '[v3.10.19-VERSION-NORMALIZE] CRITICAL FIX: Agente agora reporta versao com prefixo "v" (v3.10.19 ao inves de 3.10.19)',
  '[v3.10.19-VERSION-NORMALIZE] CRITICAL FIX: Resolve loop infinito de auto-update causado por mismatch v3.x vs 3.x',
  '[v3.10.19-VERSION-NORMALIZE] CRITICAL FIX: serve-agent-update, check-agent-updates e process-agent-updates corrigidos',
  '[v3.10.18-SCAN-PATH-FIX] CRITICAL FIX: %USERPROFILE% agora expande para usuarios reais (C:\\Users\\*), nao SYSTEM',
  '[v3.10.18-SCAN-PATH-FIX] CRITICAL FIX: Get-Item fallback para pastas protegidas (C:\\ProgramData) usando Test-Path',
  '[v3.10.18-SCAN-PATH-FIX] CRITICAL FIX: Get-ChildItem usa -Force para acessar itens ocultos/sistema',
  '[v3.10.18-SCAN-PATH-FIX] FIX: Resolve erro "Cannot bind argument to parameter Path" em C:\\ProgramData',
  '[v3.10.17-SCAN-CAMELCASE-FIX] CRITICAL FIX: Scan handler agora envia filePath/fileHash (camelCase) ao inves de file_path/file_hash',
  '[v3.10.17-SCAN-CAMELCASE-FIX] CRITICAL FIX: Resolve HTTP 400 "Missing filePath or fileHash" no scan-virus Edge Function',
  '[v3.10.17-SCAN-CAMELCASE-FIX] MELHORIA: ScanFileDialog com avisos mais claros sobre paths SYSTEM',
  '[v3.10.17-SCAN-CAMELCASE-FIX] MELHORIA: JobCreator.tsx corrigido de done para completed (Jobs v3)',
  '[v3.10.16-MULTIUSER-WEB-ACTIVITY] CRITICAL FIX: Web activity agora coleta de TODOS os perfis de usuario em C:\\Users\\*',
  '[v3.10.16-MULTIUSER-WEB-ACTIVITY] CRITICAL FIX: Resolve problema de agente SYSTEM nao ver historico dos usuarios reais',
  '[v3.10.16-MULTIUSER-WEB-ACTIVITY] FEATURE: Itera sobre todos os perfis (exceto Public, Default)',
  '[v3.10.16-MULTIUSER-WEB-ACTIVITY] FEATURE: Chrome, Firefox e Edge coletados para cada usuario individualmente',
  '[v3.10.16-MULTIUSER-WEB-ACTIVITY] FEATURE: Source agora inclui nome do usuario (chrome_history_joao, edge_history_maria)',
  '[v3.10.16-MULTIUSER-WEB-ACTIVITY] MELHORIA: Filtro melhorado para excluir dominios internos (google, microsoft, bing, mozilla)',
  '[v3.10.15-WEB-ACTIVITY-ENHANCED] FEATURE: Coleta real de historico de navegadores (Chrome, Firefox, Edge)',
  '[v3.10.15-WEB-ACTIVITY-ENHANCED] FEATURE: collect_web_activity agora coleta ate 500 dominios de multiplas fontes',
  '[v3.10.15-WEB-ACTIVITY-ENHANCED] FEATURE: Copia temporaria de arquivos SQLite bloqueados (History, places.sqlite)',
  '[v3.10.15-WEB-ACTIVITY-ENHANCED] FEATURE: Extracao de URLs via regex de arquivos binarios SQLite',
  '[v3.10.15-WEB-ACTIVITY-ENHANCED] MELHORIA: Deduplicacao de dominios entre todas as fontes (DNS + 3 navegadores)',
  '[v3.10.15-WEB-ACTIVITY-ENHANCED] MELHORIA: Logging detalhado por fonte (DNS cache, Chrome, Firefox, Edge)',
  '[v3.10.14-NO-EXIT-ON-UPDATE] CRITICAL FIX: Removido exit 0 apos auto-update bem sucedido',
  '[v3.10.14-NO-EXIT-ON-UPDATE] CRITICAL FIX: Agente continua rodando apos update (nao morre mais apos 24h)',
  '[v3.10.14-NO-EXIT-ON-UPDATE] CRITICAL FIX: Nova versao sera usada no proximo boot do sistema',
  '[v3.10.14-NO-EXIT-ON-UPDATE] FIX: Resolve problema de "agente offline apos 24h" definitivamente',
  '[v3.10.14-NO-EXIT-ON-UPDATE] MELHORIA: Agente opera 24/7 sem interrupcao mesmo durante auto-updates',
  '[v3.10.13-AUTO-UPDATE-SAFE] CRITICAL FIX: Auto-update envolvido em try-catch, exit 0 APENAS se sucesso',
  '[v3.10.13-AUTO-UPDATE-SAFE] CRITICAL FIX: Agente continua funcionando se update_agent falhar (nao morre mais)',
  '[v3.10.13-AUTO-UPDATE-SAFE] CRITICAL FIX: Elimina comportamento de "agente offline apos 24h" causado por exit incondicional',
  '[v3.10.13-AUTO-UPDATE-SAFE] MELHORIA: ScanFileDialog avisa sobre paths de usuario inacessiveis pela conta SYSTEM',
  '[v3.10.13-AUTO-UPDATE-SAFE] MELHORIA: Frontend sugere paths validos (C:\\Windows, C:\\Program Files, C:\\Temp)',
  '[v3.10.12-UPDATE-PATH-AGENTNAME-FIX] CRITICAL FIX: Handler update_agent usa caminho dinamico C:\\CyberShield\\cybershield-agent-$AgentName.ps1',
  '[v3.10.12-UPDATE-PATH-AGENTNAME-FIX] CRITICAL FIX: Resolve "arquivo nao encontrado" quando instalador salva script com nome do agente',
  '[v3.10.12-UPDATE-PATH-AGENTNAME-FIX] FIX: Elimina hardcoded v3.ps1, agora usa $Global:AgentName dinamicamente',
  '[v3.10.11-SCAN-DIRECTORY-FIX] CRITICAL FIX: Handler scan expande variaveis ambiente (%USERPROFILE%, %TEMP%) automaticamente',
  '[v3.10.11-SCAN-DIRECTORY-FIX] CRITICAL FIX: Handler scan detecta diretorios e escaneia arquivos executaveis dentro',
  '[v3.10.11-SCAN-DIRECTORY-FIX] FIX: Resolve erro "Arquivo nao encontrado" ao escanear paths com variaveis Windows',
  '[v3.10.11-SCAN-DIRECTORY-FIX] FIX: Resolve erro "Nao e possivel chamar metodo em expressao de valor nulo" ao escanear diretorios',
  '[v3.10.11-SCAN-DIRECTORY-FIX] MELHORIA: Scan de diretorio lista ate 10 executaveis (.exe, .dll, .bat, .ps1, etc)',
  '[v3.10.10-UPDATE-PATH-FIX] CRITICAL FIX: Handler update_agent usa caminho absoluto C:\\CyberShield\\cybershield-agent-v3.ps1',
  '[v3.10.10-UPDATE-PATH-FIX] CRITICAL FIX: Resolve "arquivo nao encontrado" quando PSCommandPath vazio em Scheduled Task',
  '[v3.10.10-UPDATE-PATH-FIX] MELHORIA: Rate limit submit-software-inventory aumentado de 30 para 60 req/hora',
  '[v3.10.9-PSCUSTOMOBJECT-FIX] CRITICAL FIX: Linhas 620 e 766 - $Job.ContainsKey("payload") substituido por $null -ne $Job.payload',
  '[v3.10.9-PSCUSTOMOBJECT-FIX] CRITICAL FIX: ContainsKey() nao funciona em PSCustomObject (retornado por ConvertFrom-Json)',
  '[v3.10.9-PSCUSTOMOBJECT-FIX] CRITICAL FIX: Resolve erro MethodNotFound em Invoke-WebActivityJob e Invoke-RestartServiceJob',
  '[v3.10.9-PSCUSTOMOBJECT-FIX] VALIDACAO: SHA256 correto calculado e registrado em agent_releases',
  '[v3.10.8-AGENT-ID-FIX] CRITICAL FIX: poll-jobs Edge Function agora retorna agent_id no objeto de resposta',
  '[v3.10.8-AGENT-ID-FIX] CRITICAL FIX: Handlers de seguranca (software_inventory, vuln_scan, antivirus, web_activity) usam $Job.agent_id',
  '[v3.10.8-AGENT-ID-FIX] FIX: Elimina erro 400 "agent_id violates not-null constraint" em jobs de seguranca',
  '[v3.10.8-AGENT-ID-FIX] FIX: Todos os security jobs agora completam com sucesso e populam tabelas corretamente',
  '[v3.10.7-FINAL-FIX] CRITICAL FIX: Bug #1 - scan handler removeu try/catch redundante que usava $result nao declarada',
  '[v3.10.7-FINAL-FIX] CRITICAL FIX: Bug #2 - scan handler corrigido para usar -Path ao inves de -Uri em Invoke-SecureRequest',
  '[v3.10.7-FINAL-FIX] CRITICAL FIX: Bug #3 - update_agent handler corrigido para usar -Path ao inves de -Uri',
  '[v3.10.7-FINAL-FIX] CRITICAL FIX: Bug #4 - Handlers de seguranca agora extraem $output de $result.output corretamente',
  '[v3.10.7-FINAL-FIX] CRITICAL FIX: Bug #5 - Metricas aparecem apos 5 minutos (comportamento correto mantido)',
  '[v3.10.7-FINAL-FIX] CRITICAL FIX: Bug #6 - Stuck jobs eliminados com correcao dos bugs acima',
  '[v3.10.7-FINAL-FIX] VALIDACAO: Testado em VM testepc2 com todos os tipos de jobs (scan, update_agent, security)',
  '[v3.10.5-UPDATE-FIX] CRITICAL FIX: Handler update_agent agora usa $output ao inves de variavel $result nao declarada',
  '[v3.10.5-UPDATE-FIX] CRITICAL FIX: Corrige erro "Exception setting property error" que impedia auto-update',
  '[v3.10.5-UPDATE-FIX] CRITICAL FIX: update_agent jobs agora completam corretamente permitindo auto-update funcionar',
  '[v3.10.4-UTF8-FIX] CRITICAL FIX: Forcado UTF-8 encoding em Invoke-SecureRequest para consistencia HMAC',
  '[v3.10.4-UTF8-FIX] CRITICAL FIX: Body JSON convertido para UTF-8 bytes antes de enviar (resolve erro 401 em submit-job-result)',
  '[v3.10.4-UTF8-FIX] CRITICAL FIX: HMAC agora calcula assinatura identica no agente PowerShell e backend Deno',
  '[v3.10.3-TLS-COMPLETE] CRITICAL FIX: TLS 1.2 no comando irm (resolve erro de download em Windows Server)',
  '[v3.10.3-TLS-COMPLETE] CRITICAL FIX: TLS 1.2 no installer template (resolve health check)',
  '[v3.10.3-TLS-COMPLETE] MELHORIA: TLS 1.2 em 3 camadas (download + installer + agent) para compatibilidade total',
  '[v3.10.2-TLS-FIX] CRITICAL FIX: Forcando TLS 1.2 no agente para compatibilidade com firewalls corporativos (pfSense)',
  '[v3.10.2-TLS-FIX] CRITICAL FIX: Configuracao automatica de proxy do sistema para ambientes corporativos',
  '[v3.10.2-TLS-FIX] FIX: Resolve erro "Nao foi possivel criar um canal seguro para SSL/TLS" em Windows Server',
  '[v3.10.2-TLS-FIX] MELHORIA: Heartbeat agora funciona atraves de firewalls Cloudflare/Supabase',
  '[v3.10.1-AGGRESSIVE-CLEANUP] FIX: Encerra processos PowerShell do agente antes da reinstalacao',
  '[v3.10.1-AGGRESSIVE-CLEANUP] FIX: Remove log antigo do agente preventivamente',
  '[v3.10.1-AGGRESSIVE-CLEANUP] FIX: Teste de escrita no log com retry (3 tentativas com 2s de intervalo)',
  '[v3.10.1-AGGRESSIVE-CLEANUP] FIX: Resolve erro "O fluxo nao era legivel" causado por log travado',
  '[v3.10.0-SECURITY-FEATURES] FEATURE: Software inventory collection (software_inventory_collect job)',
  '[v3.10.0-SECURITY-FEATURES] FEATURE: Light vulnerability scanner (light_vuln_scan job)',
  '[v3.10.0-SECURITY-FEATURES] FEATURE: Antivirus status collection (collect_antivirus_status job)',
  '[v3.10.0-SECURITY-FEATURES] FEATURE: Web activity tracking via DNS cache (collect_web_activity job)',
  '[v3.10.0-SECURITY-FEATURES] FEATURE: Auto-remediation - fix firewall (fix_firewall job)',
  '[v3.10.0-SECURITY-FEATURES] FEATURE: Auto-remediation - restart service (restart_service job)',
  '[v3.10.0-SECURITY-FEATURES] NEW: 12 tabelas de seguranca: software_inventory, vuln_findings, antivirus_status, agent_web_activity, etc',
  '[v3.10.0-SECURITY-FEATURES] NEW: 6 Edge Functions para coleta e analise de dados de seguranca',
  '[v3.9.1-JOB-TYPE-FIX] CRITICAL FIX: Submit-JobResult agora aceita [object] ao inves de [hashtable]',
  '[v3.9.1-JOB-TYPE-FIX] CRITICAL FIX: Jobs report agora completam corretamente (nao mais crash PSCustomObject)',
  '[v3.9.1-JOB-TYPE-FIX] FIX: Tipo do parametro $Output mudado para [object] para aceitar PSCustomObject',
  '[v3.9.0-AUTO-UPDATE] FEATURE: Agente verifica updates automaticamente a cada 24h via check-agent-updates',
  '[v3.9.0-AUTO-UPDATE] FEATURE: Auto-aplica updates quando nova versao disponivel (sem reinstalacao)',
  '[v3.9.0-AUTO-UPDATE] FEATURE: Edge Function register-agent-release para registrar novas versoes',
  '[v3.9.0-AUTO-UPDATE] FEATURE: Edge Function process-agent-updates com cron para push updates',
  '[v3.9.0-AUTO-UPDATE] MELHORIA: Tabelas agent_releases e agent_versions populadas com v3.8.0',
  '[v3.8.0-REALTIME-OS-TYPE-FIX] CRITICAL FIX: Agente envia os_type ao inves de platform no heartbeat',
  '[v3.8.0-REALTIME-OS-TYPE-FIX] CRITICAL FIX: Heartbeat aceita tanto os_type quanto platform (retrocompatibilidade)',
  '[v3.8.0-REALTIME-OS-TYPE-FIX] CRITICAL FIX: Realtime habilitado para agent_system_metrics e system_alerts',
  '[v3.8.0-REALTIME-OS-TYPE-FIX] CRITICAL FIX: Agentes existentes com os_type NULL atualizados para "windows"',
  '[v3.8.0-REALTIME-OS-TYPE-FIX] MELHORIA: Dashboard agora atualiza metricas em tempo real',
  '[v3.7.0-METRICS-WMI-FALLBACK] CRITICAL FIX: Cleanup jobs agora deleta jobs de qualquer idade (older_than_days: 0)',
  '[v3.7.0-METRICS-WMI-FALLBACK] CRITICAL FIX: Metricas CPU/RAM/Disco com WMI fallback quando Get-Counter falhar',
  '[v3.7.0-METRICS-WMI-FALLBACK] FIX: CPU usa Get-Counter primeiro, fallback para Win32_Processor.LoadPercentage',
  '[v3.7.0-METRICS-WMI-FALLBACK] FIX: RAM sempre via WMI Win32_OperatingSystem (mais confiavel)',
  '[v3.7.0-METRICS-WMI-FALLBACK] FIX: Disco usa Get-PSDrive primeiro, fallback para Win32_LogicalDisk',
  '[v3.7.0-METRICS-WMI-FALLBACK] MELHORIA: Jobs tipo report agora funcionam em VMs sem Performance Counters',
  '[v3.6.1-TELEMETRY-HMAC-FIX] CRITICAL FIX: Telemetria agora usa HMAC (X-Agent-Token + X-HMAC-Signature)',
  '[v3.6.1-TELEMETRY-HMAC-FIX] NOVO: Funcoes Convert-HexToBytes e Get-HmacSignature copiadas do agent',
  '[v3.6.1-TELEMETRY-HMAC-FIX] FIX: Installer envia post_installation com credenciais do agente',
  '[v3.6.1-TELEMETRY-HMAC-FIX] FIX: track-installation-event aceita qualquer event_type com HMAC valido',
  '[v3.6.1-TELEMETRY-HMAC-FIX] FIX: Fallback para telemetria anonima se agent ja existir (compatibilidade)',
  '[v3.6.0-METRICS-FIX] CRITICAL FIX: Metricas agora sao REALMENTE enviadas via POST submit-system-metrics',
  '[v3.6.0-METRICS-FIX] NOVO: Funcao Send-SystemMetrics envia payload estruturado para backend',
  '[v3.6.0-METRICS-FIX] FIX: Loop principal parseia JSON de Invoke-ReportJob e envia via HTTP',
  '[v3.6.0-METRICS-FIX] FIX: Logs agora mostram "CPU=XX%, RAM=YY%, Disco=ZZ%" quando metricas sao enviadas',
  '[v3.5.0-METRICS-AUTO] NOVO: Envio automatico de metricas a cada 5min no loop principal',
  '[v3.5.0-METRICS-AUTO] FIX: Calculadora de preco dinamica baseada em tiers (Landing)',
  '[v3.5.0-METRICS-AUTO] FIX: Dashboard com validacao robusta de agents online',
  '[v3.5.0-METRICS-AUTO] FIX: Telemetria aceita X-Agent-Token para post_installation (nao apenas installation_failed)',
  '[v3.5.0-METRICS-AUTO] NOVO: Cleanup automatico de jobs stuck (delivered >1h)',
  'FIX: Corrige header de versao do script (v3.0.0 -> v3.4.0-REPORT-SUPPORT)',
  'FIX: Sincroniza version string entre source e embedded script',
  'NOVO: Adiciona suporte para jobs do tipo "report" com coleta de metricas do sistema',
  'NOVO: Funcao Invoke-ReportJob coleta CPU, memoria e disco (uso de percentual)',
  'NOVO: Logging de rede em todas as requisicoes HTTP (method + URL + status)',
  'MELHORIA: Switch de tipos de job agora suporta: integration_test, collect_info, report, scan, update_agent',
  'PREVIO: Corrige InvalidVariableReferenceWithDrive no payload HMAC (linha 199)',
  'PREVIO: Substitui "$timestamp:$nonce:$bodyJson" por formatacao explicita \'{0}:{1}:{2}\' -f',
  'PREVIO: Usa operador -f para garantir compatibilidade total com PowerShell 5.1',
  'PREVIO: Diagnostico avancado de restricoes de seguranca (GPO, AppLocker, LanguageMode, AV/EDR)',
  'PREVIO: Detecta GPO forcando ExecutionPolicy AllSigned/Restricted',
  'PREVIO: Detecta Constrained Language Mode (Device Guard/WDAC)',
  'PREVIO: Testa AppLocker com execucao basica de script',
  'PREVIO: Verifica eventos do Windows Defender relacionados a PowerShell',
  'PREVIO: Detecta Device Guard / WDAC Code Integrity enforcement',
  'PREVIO: Script standalone diagnose-security-restrictions.ps1',
  'PREVIO: Adiciona Unblock-File apos salvar script do agente',
  'PREVIO: Adiciona fallback para remover Zone.Identifier manualmente',
  'PREVIO: ExecutionPolicy alterado de Bypass para Unrestricted',
  'Adiciona validacao de Zone.Identifier antes e depois do desbloqueio',
  'Corrige PSSecurityException: UnauthorizedAccess em ambientes restritos',
  'PREVIO: Scheduled Task arguments com double-double quotes ("")',
  'Corrige erro 4294770688 (argumentos mal formatados) causado por escaping incorreto',
  'PREVIO: Write-InstallerLog movida para ANTES de qualquer uso (linha ~57)',
  'Criacao de pastas agora e silenciosa (FASE 0), logging inicia na FASE 1',
  'Corrige erro: The term Write-InstallerLog is not recognized',
  'Previo: LINE-CONTINUATION-REMOVED + InvalidVariableReferenceWithDrive fixes',
  'Code Guardian System valida automaticamente sintaxe PowerShell 5.1',
];

export const KNOWN_ISSUES_FIXED = [
  'CRITICAL: Jobs nao completavam devido a erro "Nao e possivel converter PSCustomObject para Hashtable" (v3.9.1)',
  'CRITICAL: Submit-JobResult esperava [hashtable] mas recebia PSCustomObject de ConvertFrom-Json',
  'CRITICAL: Cleanup jobs nao deletava nada (older_than_days: 7 bloqueava jobs recentes)',
  'CRITICAL: Metricas N/A em VMs sem Performance Counters habilitados',
  'CRITICAL: Get-Counter falhava silenciosamente, sem fallback para WMI',
  'CRITICAL: Jobs tipo report falhavam completamente em ambientes restritos',
  'InvalidVariableReferenceWithDrive: PowerShell 5.1 interpretava :$ como drive reference no payload HMAC (CRITICAL)',
  'PSSecurityException ao executar script como SYSTEM (CRITICAL)',
  'Zone.Identifier bloqueando execucao mesmo com -ExecutionPolicy Bypass',
  'UnauthorizedAccess em ambientes com ExecutionPolicy restritiva',
  'Script marcado como "da internet" impede execucao pela Scheduled Task',
  'Task Scheduler Error 4294770688: argumentos mal formatados (CRITICAL)',
  'Backtick-quote escaping incompativel com New-ScheduledTaskAction',
  'The term Write-InstallerLog is not recognized as the name of a cmdlet',
  'ParserError: ExpectedValueExpression apos operador + (continuacao de linha)',
  'InvalidVariableReferenceWithDrive: uso de $_ em mensagens de log',
  'Instalador falhava com erros de parse antes de executar',
  'Agent nao conseguia logar erros corretamente',
  'Continuacoes de linha do PowerShell causando problemas em String.raw',
];

/**
 * Retorna string formatada para logs
 */
export function getVersionInfo(): string {
  return `Installer v${INSTALLER_VERSION} (${LAST_UPDATED})`;
}
