
REVOKE EXECUTE ON FUNCTION public.aggregate_honeypot_hourly() FROM anon;
REVOKE EXECUTE ON FUNCTION public.aggregate_honeypot_hourly_stats() FROM anon;
REVOKE EXECUTE ON FUNCTION public.audit_credential_rotation() FROM anon;
REVOKE EXECUTE ON FUNCTION public.calculate_evidence_log_hash() FROM anon;
REVOKE EXECUTE ON FUNCTION public.calculate_security_log_hash() FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_honeypot_rate_limit_v2(p_identifier_hash text, p_max_requests integer, p_bucket_seconds integer, p_block_seconds integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_expired_cache() FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_honeypot_old_data(p_retention_days integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_honeypot_rate_data(p_older_than_minutes integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_monthly_partitions(p_table_name text, p_partition_column text, p_months_ahead integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_telemetry_partitions() FROM anon;
REVOKE EXECUTE ON FUNCTION public.drop_old_partitions(p_table_name text, p_retention_months integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.drop_old_telemetry_partitions(p_retention_days integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.ensure_partition_rls() FROM anon;
REVOKE EXECUTE ON FUNCTION public.ensure_scim_api_key() FROM anon;
REVOKE EXECUTE ON FUNCTION public.generate_scim_api_key() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_agent_network_events(p_agent_id uuid, p_tenant_id uuid, p_limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_agent_processes(p_agent_id uuid, p_tenant_id uuid, p_limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_autonomy_metrics(p_tenant_id uuid, p_days integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_cached_value(p_key text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_decision_timeline(p_tenant_id uuid, p_limit integer, p_rule_code text, p_agent_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_honeypot_stats(p_tenant_id uuid, p_hours integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_pending_events(p_tenant_id text, p_limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_trace_timeline(p_trace_id text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.guard_role_self_promotion() FROM anon;
REVOKE EXECUTE ON FUNCTION public.invalidate_cache_prefix(p_prefix text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_feature_enabled(p_flag_key text, p_tenant_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_table_migrated(p_table_name text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_tenant_admin() FROM anon;
REVOKE EXECUTE ON FUNCTION public.maintain_partitions() FROM anon;
REVOKE EXECUTE ON FUNCTION public.migrate_telemetry_batch(p_table_name text, p_batch_size integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.redirect_event_buffer_insert() FROM anon;
REVOKE EXECUTE ON FUNCTION public.redirect_network_events_insert() FROM anon;
REVOKE EXECUTE ON FUNCTION public.redirect_process_events_insert() FROM anon;
REVOKE EXECUTE ON FUNCTION public.revoke_tokens_on_archive() FROM anon;
REVOKE EXECUTE ON FUNCTION public.run_integrity_sentinel() FROM anon;
REVOKE EXECUTE ON FUNCTION public.run_partition_maintenance() FROM anon;
REVOKE EXECUTE ON FUNCTION public.set_cached_value(p_key text, p_value jsonb, p_ttl_seconds integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.set_signing_key_expiry() FROM anon;
REVOKE EXECUTE ON FUNCTION public.validate_audit_trail_integrity(p_tenant_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.verify_evidence_log_chain(p_tenant_id uuid, p_start_date timestamp with time zone, p_end_date timestamp with time zone) FROM anon;
REVOKE EXECUTE ON FUNCTION public.verify_security_log_chain(p_tenant_id uuid, p_start_date timestamp with time zone, p_end_date timestamp with time zone) FROM anon;
