/**
 * generate-deploy-package Edge Function (P2)
 * 
 * Zero-touch Deployment: Generates deployment scripts for Intune, GPO, and RMM.
 * Returns ready-to-use scripts with the enrollment key embedded.
 * 
 * Authentication: JWT (dashboard user)
 */

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.74.0';
import { corsHeaders } from '../_shared/cors.ts';

type Platform = 'intune' | 'gpo' | 'rmm' | 'manual';

function generateIntuneScript(enrollmentKey: string, supabaseUrl: string, tenantName: string): string {
  return `<#
.SYNOPSIS
    CyberShield Agent - Intune Deployment Package
    Generated for: ${tenantName}
    
.DESCRIPTION
    Deploy as Win32 App (.intunewin) or PowerShell script via Intune.
    Detection Rule: File exists C:\\CyberShield\\config.json
    
.NOTES
    Platform: Microsoft Intune / Endpoint Manager
    Execution Context: SYSTEM
    Auto-generated by CyberShield Deploy Engine
#>

# === CONFIGURATION ===
\$ErrorActionPreference = 'Stop'
\$EnrollmentKey = '${enrollmentKey}'
\$ServerUrl = '${supabaseUrl}'
\$InstallDir = 'C:\\CyberShield'
\$LogFile = "\$env:TEMP\\cybershield-install.log"

function Write-InstallLog {
    param([string]\$Message)
    \$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    "\$timestamp - \$Message" | Out-File -FilePath \$LogFile -Append -Encoding UTF8
    Write-Host \$Message
}

try {
    Write-InstallLog "CyberShield Intune deployment starting..."
    
    # Check if already installed
    if (Test-Path "\$InstallDir\\config.json") {
        Write-InstallLog "CyberShield already installed. Checking version..."
        \$config = Get-Content "\$InstallDir\\config.json" -Raw | ConvertFrom-Json
        Write-InstallLog "Current version: \$(\$config.version). Skipping install."
        exit 0
    }
    
    # Download installer via enrollment endpoint
    Write-InstallLog "Downloading agent from server..."
    \$headers = @{
        'Content-Type' = 'application/json'
    }
    \$body = @{
        enrollment_key = \$EnrollmentKey
        hostname = \$env:COMPUTERNAME
        deployment_method = 'intune'
    } | ConvertTo-Json
    
    \$response = Invoke-RestMethod -Uri "\$ServerUrl/functions/v1/enroll-agent" \`
        -Method POST \`
        -Headers \$headers \`
        -Body \$body \`
        -TimeoutSec 120
    
    if (\$response.success) {
        Write-InstallLog "Enrollment successful. Agent ID: \$(\$response.agent_id)"
        
        # Create install directory
        if (-not (Test-Path \$InstallDir)) {
            New-Item -Path \$InstallDir -ItemType Directory -Force | Out-Null
        }
        
        # Save config
        \$config = @{
            agent_id = \$response.agent_id
            token = \$response.token
            server_url = \$ServerUrl
            version = "enrolled"
            deployed_via = "intune"
            deployed_at = (Get-Date -Format "o")
        } | ConvertTo-Json
        
        Set-Content -Path "\$InstallDir\\config.json" -Value \$config -Encoding UTF8
        
        # Download and execute the agent script
        if (\$response.script_url) {
            Write-InstallLog "Downloading agent script..."
            Invoke-WebRequest -Uri \$response.script_url -OutFile "\$InstallDir\\cybershield-agent.ps1" -TimeoutSec 60
        }
        
        # Register scheduled task
        \$action = New-ScheduledTaskAction -Execute 'powershell.exe' \`
            -Argument "-ExecutionPolicy Bypass -WindowStyle Hidden -File \$InstallDir\\cybershield-agent.ps1"
        \$trigger = New-ScheduledTaskTrigger -AtStartup
        \$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries \`
            -StartWhenAvailable -RestartCount 5 -RestartInterval (New-TimeSpan -Minutes 5) \`
            -ExecutionTimeLimit (New-TimeSpan -Days 365)
        \$principal = New-ScheduledTaskPrincipal -UserId "SYSTEM" -RunLevel Highest -LogonType ServiceAccount
        
        Register-ScheduledTask -TaskName "CyberShield Agent" -Action \$action -Trigger \$trigger \`
            -Settings \$settings -Principal \$principal -Force
        
        Start-ScheduledTask -TaskName "CyberShield Agent"
        
        Write-InstallLog "CyberShield agent installed and started successfully."
        exit 0
    } else {
        Write-InstallLog "Enrollment failed: \$(\$response.error)"
        exit 1
    }
} catch {
    Write-InstallLog "FATAL ERROR: \$(\$_.Exception.Message)"
    exit 1
}`;
}

function generateGPOScript(enrollmentKey: string, supabaseUrl: string, tenantName: string): string {
  return `@echo off
REM ============================================
REM CyberShield Agent - GPO Deployment Script
REM Generated for: ${tenantName}
REM 
REM Usage: Deploy as Computer Startup Script via GPO
REM Path: Computer Configuration > Policies > Windows Settings > Scripts > Startup
REM ============================================

SET ENROLLMENT_KEY=${enrollmentKey}
SET SERVER_URL=${supabaseUrl}
SET INSTALL_DIR=C:\\CyberShield

REM Check if already installed
IF EXIST "%INSTALL_DIR%\\config.json" (
    echo CyberShield already installed. Skipping.
    exit /b 0
)

REM Run PowerShell enrollment
powershell.exe -ExecutionPolicy Bypass -NoProfile -Command ^
  "& { ^
    try { ^
      \$body = @{ enrollment_key='%ENROLLMENT_KEY%'; hostname=\$env:COMPUTERNAME; deployment_method='gpo' } | ConvertTo-Json; ^
      \$resp = Invoke-RestMethod -Uri '%SERVER_URL%/functions/v1/enroll-agent' -Method POST -Body \$body -ContentType 'application/json' -TimeoutSec 120; ^
      if (\$resp.success) { ^
        New-Item -Path '%INSTALL_DIR%' -ItemType Directory -Force | Out-Null; ^
        @{agent_id=\$resp.agent_id; token=\$resp.token; server_url='%SERVER_URL%'; deployed_via='gpo'} | ConvertTo-Json | Set-Content '%INSTALL_DIR%\\config.json'; ^
        Write-Host 'CyberShield enrolled successfully'; ^
        exit 0 ^
      } else { Write-Host 'Enrollment failed'; exit 1 } ^
    } catch { Write-Host \$_.Exception.Message; exit 1 } ^
  }"`;
}

function generateRMMScript(enrollmentKey: string, supabaseUrl: string, tenantName: string): string {
  return `# CyberShield Agent - RMM One-Liner Deployment
# Generated for: ${tenantName}
# Compatible with: NinjaOne, Atera, Datto RMM, ConnectWise Automate
#
# Usage: Paste as a PowerShell script in your RMM platform
# Execution Context: Run as SYSTEM

$ErrorActionPreference = 'Stop'
if (Test-Path 'C:\\CyberShield\\config.json') { Write-Host 'Already installed'; exit 0 }
try {
    $body = @{ enrollment_key='${enrollmentKey}'; hostname=$env:COMPUTERNAME; deployment_method='rmm' } | ConvertTo-Json
    $resp = Invoke-RestMethod -Uri '${supabaseUrl}/functions/v1/enroll-agent' -Method POST -Body $body -ContentType 'application/json' -TimeoutSec 120
    if ($resp.success) {
        New-Item -Path 'C:\\CyberShield' -ItemType Directory -Force | Out-Null
        @{agent_id=$resp.agent_id; token=$resp.token; server_url='${supabaseUrl}'; deployed_via='rmm'; deployed_at=(Get-Date -Format 'o')} | ConvertTo-Json | Set-Content 'C:\\CyberShield\\config.json'
        Write-Host "CyberShield enrolled: $($resp.agent_id)"
        exit 0
    } else { Write-Host "Failed: $($resp.error)"; exit 1 }
} catch { Write-Host $_.Exception.Message; exit 1 }`;
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabase = createClient(supabaseUrl, Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);

    // Authenticate via JWT
    const authHeader = req.headers.get('authorization');
    if (!authHeader) {
      return new Response(JSON.stringify({ error: 'Unauthorized' }), {
        status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    const token = authHeader.replace('Bearer ', '');
    const { data: { user }, error: userError } = await supabase.auth.getUser(token);
    if (userError || !user) {
      return new Response(JSON.stringify({ error: 'Invalid token' }), {
        status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    // Get user's tenant
    const { data: userRole } = await supabase
      .from('user_roles')
      .select('tenant_id, role')
      .eq('user_id', user.id)
      .maybeSingle();

    if (!userRole) {
      return new Response(JSON.stringify({ error: 'No tenant found' }), {
        status: 403, headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    const url = new URL(req.url);
    const platform = (url.searchParams.get('platform') || 'manual') as Platform;
    const enrollmentKeyId = url.searchParams.get('enrollment_key_id');

    if (!enrollmentKeyId) {
      return new Response(JSON.stringify({ error: 'enrollment_key_id required' }), {
        status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    // Fetch enrollment key (verify it belongs to user's tenant)
    const { data: enrollmentKey, error: ekError } = await supabase
      .from('enrollment_keys')
      .select('id, key_value, tenant_id, name')
      .eq('id', enrollmentKeyId)
      .eq('tenant_id', userRole.tenant_id)
      .eq('is_active', true)
      .maybeSingle();

    if (ekError || !enrollmentKey) {
      return new Response(JSON.stringify({ error: 'Enrollment key not found' }), {
        status: 404, headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    // Get tenant name
    const { data: tenant } = await supabase
      .from('tenants')
      .select('name')
      .eq('id', userRole.tenant_id)
      .maybeSingle();

    const tenantName = tenant?.name || 'CyberShield Customer';
    const keyValue = enrollmentKey.key_value;

    let script = '';
    let filename = '';
    let contentType = 'text/plain';

    switch (platform) {
      case 'intune':
        script = generateIntuneScript(keyValue, supabaseUrl, tenantName);
        filename = `CyberShield-Intune-${enrollmentKey.name || 'deploy'}.ps1`;
        break;
      case 'gpo':
        script = generateGPOScript(keyValue, supabaseUrl, tenantName);
        filename = `CyberShield-GPO-${enrollmentKey.name || 'deploy'}.bat`;
        break;
      case 'rmm':
        script = generateRMMScript(keyValue, supabaseUrl, tenantName);
        filename = `CyberShield-RMM-${enrollmentKey.name || 'deploy'}.ps1`;
        break;
      default:
        script = generateRMMScript(keyValue, supabaseUrl, tenantName);
        filename = `CyberShield-Manual-${enrollmentKey.name || 'deploy'}.ps1`;
    }

    return new Response(JSON.stringify({
      success: true,
      platform,
      filename,
      script,
      enrollment_key_name: enrollmentKey.name,
      instructions: platform === 'intune'
        ? 'Wrap this .ps1 in an .intunewin package. Detection Rule: File exists C:\\CyberShield\\config.json'
        : platform === 'gpo'
        ? 'Deploy as Computer Startup Script: Computer Configuration > Policies > Windows Settings > Scripts > Startup'
        : 'Paste as a PowerShell script in your RMM platform. Run as SYSTEM.',
    }), {
      status: 200,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (error) {
    const errorMsg = error instanceof Error ? error.message : 'Unknown error';
    return new Response(
      JSON.stringify({ success: false, error: errorMsg }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
