#!/usr/bin/env bash
# D18-2 / HF-TYPES-REGEN-01
# Mirrors the Lovable Cloud (Supabase) typegen output from the Vite source of
# truth into the Deno-side mirror used by Edge Functions.
#
# Single source of truth:
#   src/integrations/supabase/types.ts        (auto-generated by Lovable Cloud)
#
# Mirror (consumed by `supabase/functions/**`):
#   supabase/functions/_shared/database.types.ts
#
# This script is intentionally trivial: it performs a byte-for-byte copy so
# the two files cannot drift. Do NOT hand-edit either file.
set -euo pipefail

SRC="src/integrations/supabase/types.ts"
DST="supabase/functions/_shared/database.types.ts"

if [[ ! -f "$SRC" ]]; then
  echo "✗ source typegen file missing: $SRC" >&2
  exit 1
fi

mkdir -p "$(dirname "$DST")"
cp "$SRC" "$DST"
echo "✓ synced $DST  ← $SRC"
