-- Add auto_generated column to enrollment_keys table
ALTER TABLE public.enrollment_keys 
ADD COLUMN IF NOT EXISTS auto_generated BOOLEAN DEFAULT false;

-- Add comment for documentation
COMMENT ON COLUMN public.enrollment_keys.auto_generated IS 'Indicates if the key was automatically generated by the system when all previous keys expired';