ALTER TABLE public.ops_checks
ADD COLUMN IF NOT EXISTS check_type TEXT NOT NULL DEFAULT 'rpc',
ADD COLUMN IF NOT EXISTS target_url TEXT,
ADD COLUMN IF NOT EXISTS method TEXT DEFAULT 'GET',
ADD COLUMN IF NOT EXISTS timeout_ms INTEGER DEFAULT 10000;
