#!/usr/bin/env bash
#
# CyberShield Agent - Constants & FSM Definitions
#

AGENT_VERSION="v6.0.0"
POLL_INTERVAL=60
JOB_POLL_INTERVAL=30

# ECDSA P-256 Keys
SIGNING_FINGERPRINT=""
KEY_VERSION=0

# FSM States
declare -A FSM_STATES=(
    [INITIALIZING]="INITIALIZING"
    [AUTHENTICATING]="AUTHENTICATING"
    [SYNCING]="SYNCING"
    [ENFORCING]="ENFORCING"
    [DEGRADED]="DEGRADED"
    [SAFE_MODE]="SAFE_MODE"
)
CURRENT_STATE="INITIALIZING"

declare -A STATE_TRANSITIONS=(
    ["INITIALIZING"]="AUTHENTICATING SAFE_MODE"
    ["AUTHENTICATING"]="SYNCING DEGRADED SAFE_MODE"
    ["SYNCING"]="ENFORCING DEGRADED SAFE_MODE"
    ["ENFORCING"]="SYNCING DEGRADED SAFE_MODE"
    ["DEGRADED"]="AUTHENTICATING SYNCING ENFORCING SAFE_MODE"
    ["SAFE_MODE"]="INITIALIZING"
)

# Hash Chain
EXECUTION_CHAIN_LAST_HASH="genesis"
EXECUTION_CHAIN_INDEX=0

# Auto-repair thresholds
DISK_CLEANUP_THRESHOLD=95
HIGH_CPU_THRESHOLD=90
AUTO_REPAIR_DISK_CLEANUPS=0
AUTO_REPAIR_PROCESSES_KILLED=0
AUTO_REPAIR_LAST_DISK_CLEANUP=""
AUTO_REPAIR_LAST_PROCESS_KILL=""

# Network
NETWORK_TEST_HOST=""
NETWORK_TEST_PORT=443
CONSECUTIVE_NETWORK_FAILURES=0
CONSECUTIVE_HEARTBEAT_FAILURES=0
MAX_CONSECUTIVE_FAILURES=1000000

# Integrity
LAST_RUNTIME_INTEGRITY_CHECK=0
RUNTIME_INTEGRITY_INTERVAL=300
TOCTOU_CONSECUTIVE_FAILURES=0

# Process baseline
declare -a PROCESS_BASELINE=()
declare -A PROCESS_BASELINE_MAP=()

# Log buffering
LOG_BUFFER=""
LOG_BUFFER_COUNT=0
LOG_BUFFER_MAX=20
LOG_BUFFER_LAST_FLUSH=0
LOG_CALL_COUNT=0
LOG_ROTATION_CHECK_INTERVAL=100
CACHED_TIMESTAMP=""
CACHED_EPOCH=0
ADAPTIVE_MIN_SLEEP=10
LAST_CPU_PERCENT=0
